stages:
  - stage: ReleaseProd
    displayName: 'Deploy to SQL to Prod'
    dependsOn: Build
    variables:
    - group: AzureSqlConnection #1: pull in DB connection from library
    jobs:
    - deployment: MigrateDatabase
      environment: 'prod' #2: you'll need to define an env
      displayName: Migrate Database
      variables:
       namespace: prod # define some variables
      pool:
       vmImage: windows-latest # this task only works in windows
      strategy:
       runOnce:
         deploy:
          steps:
           - task: DownloadPipelineArtifact@2
             displayName: 'download migration script'
             inputs:
               artifactName: 'migrations'
               downloadPath: '$(System.ArtifactsDirectory)/migrations'
           - task: SqlAzureDacpacDeployment@1
             displayName: 'run sql migrations'
             inputs:
              azureConnectionType: connectedServiceNameARM
              azureSubscription: 'Azure subscription (6fc9dca7-98eb-4b8b-ab95-f0c82a30943e)'
              authenticationType: connectionString
              connectionString: $(azuresqlconnectionkey)
              deployType: sqlTask
              sqlFile: $(System.ArtifactsDirectory)/migrations/_AppDbContext.sql